import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import { css } from "styled-system/css";
import Navbar from "./components_custom/Navbar";
import { Center } from "styled-system/jsx";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={css({
          backgroundColor: "background",
        })}
      >
        <Navbar />
        <Center h={'full'}>
        {children}
        </Center>
      </body>
    </html>
  );
}