// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: machine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runner int32

const (
	Runner_Binary Runner = 0
	Runner_Java   Runner = 1
)

// Enum value maps for Runner.
var (
	Runner_name = map[int32]string{
		0: "Binary",
		1: "Java",
	}
	Runner_value = map[string]int32{
		"Binary": 0,
		"Java":   1,
	}
)

func (x Runner) Enum() *Runner {
	p := new(Runner)
	*p = x
	return p
}

func (x Runner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runner) Descriptor() protoreflect.EnumDescriptor {
	return file_machine_proto_enumTypes[0].Descriptor()
}

func (Runner) Type() protoreflect.EnumType {
	return &file_machine_proto_enumTypes[0]
}

func (x Runner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runner.Descriptor instead.
func (Runner) EnumDescriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{0}
}

type Sucess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sucess bool `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
}

func (x *Sucess) Reset() {
	*x = Sucess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sucess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sucess) ProtoMessage() {}

func (x *Sucess) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sucess.ProtoReflect.Descriptor instead.
func (*Sucess) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Sucess) GetSucess() bool {
	if x != nil {
		return x.Sucess
	}
	return false
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid uint32 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type StartStopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32 `protobuf:"varint,1,opt,name=User_id,json=UserId,proto3" json:"User_id,omitempty"`
	MachineId uint32 `protobuf:"varint,2,opt,name=Machine_id,json=MachineId,proto3" json:"Machine_id,omitempty"`
}

func (x *StartStopReq) Reset() {
	*x = StartStopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStopReq) ProtoMessage() {}

func (x *StartStopReq) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStopReq.ProtoReflect.Descriptor instead.
func (*StartStopReq) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{2}
}

func (x *StartStopReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartStopReq) GetMachineId() uint32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

type ConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User       *User   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	MachineId  uint32  `protobuf:"varint,2,opt,name=Machine_id,json=MachineId,proto3" json:"Machine_id,omitempty"`
	Runner     Runner  `protobuf:"varint,3,opt,name=Runner,proto3,enum=tricky.Runner" json:"Runner,omitempty"`
	BinaryPath string  `protobuf:"bytes,4,opt,name=BinaryPath,proto3" json:"BinaryPath,omitempty"`
	RemoteZip  *string `protobuf:"bytes,5,opt,name=RemoteZip,proto3,oneof" json:"RemoteZip,omitempty"`
	Files      *Dir    `protobuf:"bytes,6,opt,name=Files,proto3,oneof" json:"Files,omitempty"`
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ConfigReq) GetMachineId() uint32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *ConfigReq) GetRunner() Runner {
	if x != nil {
		return x.Runner
	}
	return Runner_Binary
}

func (x *ConfigReq) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *ConfigReq) GetRemoteZip() string {
	if x != nil && x.RemoteZip != nil {
		return *x.RemoteZip
	}
	return ""
}

func (x *ConfigReq) GetFiles() *Dir {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_machine_proto protoreflect.FileDescriptor

var file_machine_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x1a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x75, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x22, 0x1e, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x0d, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x22, 0xf8, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x72, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x52, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x09,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5a, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5a, 0x69, 0x70, 0x88, 0x01, 0x01, 0x12,
	0x26, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x44, 0x69, 0x72, 0x48, 0x01, 0x52, 0x05, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x5a, 0x69, 0x70, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x2a,
	0x1e, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x61, 0x76, 0x61, 0x10, 0x01, 0x32,
	0xca, 0x01, 0x0a, 0x06, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x74, 0x72, 0x69,
	0x63, 0x6b, 0x79, 0x2e, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x53, 0x74,
	0x6f, 0x70, 0x12, 0x15, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x74, 0x72, 0x69, 0x63,
	0x6b, 0x79, 0x2e, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0c, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x1a, 0x12, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6b,
	0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x74,
	0x72, 0x69, 0x63, 0x6b, 0x79, 0x2e, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_machine_proto_rawDescOnce sync.Once
	file_machine_proto_rawDescData = file_machine_proto_rawDesc
)

func file_machine_proto_rawDescGZIP() []byte {
	file_machine_proto_rawDescOnce.Do(func() {
		file_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_machine_proto_rawDescData)
	})
	return file_machine_proto_rawDescData
}

var file_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_machine_proto_goTypes = []any{
	(Runner)(0),          // 0: tricky.Runner
	(*Sucess)(nil),       // 1: tricky.Sucess
	(*User)(nil),         // 2: tricky.User
	(*StartStopReq)(nil), // 3: tricky.StartStop_req
	(*ConfigReq)(nil),    // 4: tricky.Config_req
	(*Dir)(nil),          // 5: tricky.Dir
}
var file_machine_proto_depIdxs = []int32{
	2, // 0: tricky.Config_req.user:type_name -> tricky.User
	0, // 1: tricky.Config_req.Runner:type_name -> tricky.Runner
	5, // 2: tricky.Config_req.Files:type_name -> tricky.Dir
	3, // 3: tricky.tricky.Start:input_type -> tricky.StartStop_req
	3, // 4: tricky.tricky.Stop:input_type -> tricky.StartStop_req
	2, // 5: tricky.tricky.GetConfig:input_type -> tricky.User
	4, // 6: tricky.tricky.ChangeConfig:input_type -> tricky.Config_req
	1, // 7: tricky.tricky.Start:output_type -> tricky.Sucess
	1, // 8: tricky.tricky.Stop:output_type -> tricky.Sucess
	4, // 9: tricky.tricky.GetConfig:output_type -> tricky.Config_req
	1, // 10: tricky.tricky.ChangeConfig:output_type -> tricky.Sucess
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_machine_proto_init() }
func file_machine_proto_init() {
	if File_machine_proto != nil {
		return
	}
	file_filesystem_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machine_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Sucess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StartStopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_machine_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machine_proto_goTypes,
		DependencyIndexes: file_machine_proto_depIdxs,
		EnumInfos:         file_machine_proto_enumTypes,
		MessageInfos:      file_machine_proto_msgTypes,
	}.Build()
	File_machine_proto = out.File
	file_machine_proto_rawDesc = nil
	file_machine_proto_goTypes = nil
	file_machine_proto_depIdxs = nil
}
